In [3]:
#02_perceptron_old.py

import tensorflow as tf 

x = [[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]]
y = [[-1],[1],[1],[1]]

w = tf.Variable([[1.0],[1.0]])
#b = tf.Variable(-0.5) #OR's bias 
b = tf.Variable(-1.5) #AND's bias 

#s_x = tf.matmul(x, w)
s = tf.add(tf.matmul(x, w), b)
o = tf.sign(s)

print(x)
print("OR OUTPUT")
print(o)


[[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]
OR OUTPUT
tf.Tensor(
[[-1.]
 [-1.]
 [-1.]
 [ 1.]], shape=(4, 1), dtype=float32)


In [4]:
#03_perceptron_old_fit.py

import tensorflow as tf 

x = [[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]]
y = [[-1],[-1],[-1],[1]]

w = tf.Variable(tf.random.uniform([2,1],-0.5,0.5)) 
b = tf.Variable(tf.zeros([1]))

opt = tf.keras.optimizers.SGD(learning_rate = 0.1) #w,b 미세조정

def forward():  #페셉트론 추론 과정
    s = tf.add(tf.matmul(x,w), b)
    o = tf.tanh(s)
    return o

def loss():  #추론값과 저답 레이블 간의 오차 계산
    o = forward()
    return tf.reduce_mean((y-o)**2)  #mean square : 제곱 평균

def train_step():   #1 step씩 훈련,  머신러닝의 훈련 한 과정
    with tf.GradientTape() as tape:
        l = loss()
        grad = tape.gradient(l ,[w,b])
        opt.apply_gradients(zip(grad, [w,b]))
          
for i in range(1000):
    train_step()
    if(i%100 ==0):
        print("loss at epoch", i, '=', loss().numpy())
        
print(w.numpy())
print(b.numpy())

o = forward()
print("prediction")
print(o)

loss at epoch 0 = 0.8918799
loss at epoch 100 = 0.15138245
loss at epoch 200 = 0.07788731
loss at epoch 300 = 0.050677713
loss at epoch 400 = 0.037015226
loss at epoch 500 = 0.028936699
loss at epoch 600 = 0.023647988
loss at epoch 700 = 0.0199372
loss at epoch 800 = 0.017199736
loss at epoch 900 = 0.0151023
[[2.609896]
 [2.609896]]
[-3.9618099]
prediction
tf.Tensor(
[[-0.99927604]
 [-0.87450427]
 [-0.87450427]
 [ 0.85050684]], shape=(4, 1), dtype=float32)
